project_id = "csyfgvtcvbyzirdqvmfc"

[functions.motor-uib]
verify_jwt = false

[functions.gerar-cdv-manual]
verify_jwt = false

[functions.consultar-sefaz]
verify_jwt = false

[functions.enviar-convite-cooperativa]
verify_jwt = false

[functions.enviar-convite-investidor]
verify_jwt = false

[functions.validar-expiracoes-entregas]
verify_jwt = false

[functions.processar-codigo-nota]
verify_jwt = false

[functions.ocr-nota-fiscal]
verify_jwt = false

[functions.buscar-produto-gtin]
verify_jwt = false

[functions.processar-entrega-validada]
verify_jwt = false

[functions.reconciliar-cdv]
verify_jwt = false

[functions.atualizar-status-quotas-cdv]
verify_jwt = false

[functions.calcular-pontos-mensais]
verify_jwt = false

[functions.calcular-pontos-esperados]
verify_jwt = false

[functions.processar-historico-residuos]
verify_jwt = false

[functions.processar-historico-educacao]
verify_jwt = false

[functions.processar-historico-embalagens]
verify_jwt = false
